fix: correct test
correct tests to catch -1 out of range BigInteger error

diff --git a/.github/workflows/new_etl_pipeline.yml b/.github/workflows/new_etl_pipeline.yml
--- a/.github/workflows/new_etl_pipeline.yml
+++ b/.github/workflows/new_etl_pipeline.yml
@@ -85,6 +85,17 @@ jobs:
             echo "Date data types check passed."
           fi
 
+      # CHQ: Step added by me
+      # New Step to catch the specific date error
+      - name: Validate Incompatible Data types with Date Error
+        run: |
+          if grep -q "OverflowError: Python integer -1 out of bounds for uint32" etl_output.log; then
+            echo "::error::ETL run failed: out of bounds error."
+            exit 1 # Exit with a non-zero status to fail the job
+          else
+            echo "All numbers in bounds."
+          fi
+
       # The validation step is correctly placed here, after the script has run
       - name: Validate Load Step Dependencies
         run: |
